# Generated by Django 4.1.7 on 2023-02-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=1024)),
                ("project_number", models.CharField(max_length=1024)),
                ("acquisition_date", models.DateTimeField(blank=True, null=True)),
                ("number_3l_code", models.CharField(max_length=1024)),
                ("project_deal_type_id", models.CharField(max_length=1024)),
                ("project_group_id", models.CharField(max_length=1024)),
                ("project_status_id", models.CharField(max_length=1024)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WTG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("WTG_number", models.CharField(max_length=1024)),
                ("WTG_Type_id", models.CharField(max_length=1024)),
                ("Region_id", models.CharField(max_length=1024)),
                ("kW", models.CharField(max_length=1024)),
                ("hub", models.CharField(max_length=1024)),
                ("rotor", models.CharField(max_length=1024)),
                ("altitude", models.CharField(max_length=1024)),
                ("COD", models.CharField(max_length=1024)),
                ("zip_code", models.CharField(max_length=1024)),
                ("WGS_84_north", models.CharField(max_length=1024)),
                ("WGS_84_east", models.CharField(max_length=1024)),
                ("gauss_krueger_zone", models.CharField(max_length=1024)),
                ("gauss_krueger_north", models.CharField(max_length=1024)),
                ("gauss_krueger_east", models.CharField(max_length=1024)),
                ("town_id", models.CharField(max_length=1024)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.project",
                    ),
                ),
            ],
        ),
    ]
